; Trace Windows installer — generated by Hermes build (1.3.1).
; Single-file EXE, installs Trace.exe + Flutter runtime beside it.

#define MyAppName "Trace"
#define MyAppVersion "1.3.1"
#define MyAppPublisher "Trace"
#define MyAppExeName "Trace.exe"

[Setup]
AppId={{TRACE-APP-1-0-0-UNIQUE}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputBaseFilename=Trace-1.3.1-Setup
Compression=lzma2/max
SolidCompression=yes
ArchitecturesAllowed=x64compatible
PrivilegesRequired=lowest
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "C:\Users\K1\Desktop\Projects\Trace\apps\trace_flutter\build\windows\x64\runner\Release\Trace.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\K1\Desktop\Projects\Trace\apps\trace_flutter\build\windows\x64\runner\Release\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\K1\Desktop\Projects\Trace\apps\trace_flutter\build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\K1\Desktop\Projects\Trace\apps\trace_flutter\build\windows\x64\runner\Release\*.dll"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
